apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: pvc-dependencies
  labels:
    opendatahub.io/dashboard: "true"
  name: pvc-dependencies
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
