apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: custom-pyspark-job-ui
  namespace: default
spec:
  volumes:
  - name: app-volume
    emptyDir: {}
  sparkConf:
    spark.eventLog.enabled: "false"
    spark.ui.proxyRedirectUri: "/jobs/" # Adjust based on your Ingress path
  type: Python
  mode: cluster
  image: image-registry.openshift-image-registry.svc:5000/custom-spark-job/my-custom-python-image
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/project/app.py
  sparkVersion: 4.0.0
  driver:
    volumeMounts:
    - name: app-volume
      mountPath: /opt/app-root/src/
    labels:
      version: 4.0.0
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsGroup: 185
      runAsUser: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
  executor:
    volumeMounts:
    - name: app-volume
      mountPath: /opt/app-root/src/
    labels:
      version: 4.0.0
    instances: 2
    cores: 1
    memory: 512m
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsGroup: 185
      runAsUser: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault